#!/bin/sh
# xrandr script for a x220 with the big replicator docking station and 2 big screens

xrandr --output DP3 --off --output DP2 --off --output DP1 --off --output HDMI3 -    -off --output HDMI2 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --    off --output LVDS1 --off --output VGA1 --mode 1920x1080 --pos 1920x0 --rotate normal

